### PR TITLE
Awesomes books using ES6

### PR DESCRIPTION
**Pull request by zairdon20**
In the following milestone i implemented:

- Used ES6 syntax.

- Divided the code into modules. Saved each module in a separate file in the modules dir. Import modules in the index.js file.

### CODE REVIEW

**Comment by moise10r** [comment]
Hey @zairdon20, is it the to-do list app or the Awesome books??

**Comment by zairdon20** [comment]
Sorry this link I was supposed to send for day two.

**Comment by moise10r** [comment]
Which project are you working on?
I've cloned your project and it's the to-do list app instead of the  Awesome books

**Comment by zairdon20** [comment]
To do list  structure for day 2.

**Comment by moise10r** [comment]
I will make it invalid in order to you help you submitting at the right place

**Comment by zairdon20** [comment]
Yes please, thanks

**Review by moise10r — COMMENTED** [review]
Hi @zairdon20, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project in the wrong place

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mikethreels — APPROVED** [review]
Hi Josphat, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
